wav_path: ""
cut: "_, -"
ignore: "AP,SP,EP,R,-,B"
VCV_mode: 2
cv_sum: "1,3,1,1,2"
vc_sum: "5,0,2,1,2"
vv_sum: "0,0,0,0,0"
cv_offset: "0,0,0,0,-50"
vc_offset: "0,0,0,0,0"
pitch: ""
CV_repeat: 1
VC_repeat: 0
cover: "Y"
