# 字符分隔符
Separator: _, -
# 忽略ds音素
Ignore_phonemes: AP, SP, EP, R, -, B
# -CV和CV规则：左线占比,固定的占比,右线占比,预发声不变,交叉占比
cv_sum: 1,3,1.5,1,2
# VC和VV规则：左线占比,固定的占比,右线占比,预发声不变,交叉占比
vc_sum: 3,0,2,1,2
vv_sum: 3,3,1.5,1,3
# 偏移数值(左-右+,单位ms)
# (左线偏移后，其他线都要自己进行同步偏移数值)
# (右线的数值，在处理前会自动转为正数，所以不需要考虑正负问题)
# 示例：cv_sum=10,-10,-10,-10,-10（这样调整才能保持线位置不变）
# -CV和CV规则：左线偏移,固定偏移,右线偏移,预发声偏移,交叉偏移
cv_offset: 0,0,0,0,0
# VC和VV规则：左线偏移,固定的偏移,右线偏移,预发声偏移,交叉偏移
vc_offset: 0,0,0,0,0
# 保留多少个重复音素
CV_repeat: 1
VC_repeat: 1
